const modal=document.getElementById('cvDetailModal');const title=document.getElementById('cvDetailTitle');const eyebrow=document.getElementById('cvDetailEyebrow');const intro=document.getElementById('cvDetailIntro');const sections=document.getElementById('cvDetailSections');const cta=document.getElementById('cvDetailCta');let lastTrigger=null;
const details={
capabilities:{eyebrow:'CREATIVE CAPABILITIES',title:'Design across formats, guided by one clear direction',intro:'I handle visual communication from the first content structure through production and delivery.',cta:'projects.html',sections:[['Campaign and social design','Campaign systems, announcements, carousels, enrollment materials, and platform-ready social content.'],['Publication and layout','Brochures, programs, catalogs, event materials, presentations, and large-format production.'],['Brand and visual support','Logo systems, identity applications, mockups, product presentation, and reusable templates.'],['Web and creative systems','Responsive websites, trackers, forms, dashboards, and lightweight workflow tools.']]},
tools:{eyebrow:'APPLICATIONS & WORKFLOW',title:'Tools selected around the output',intro:'Software supports the process, but hierarchy, direction, refinement, and production judgment remain the core of the work.',cta:'projects.html',sections:[['Adobe production','Photoshop, Illustrator, and InDesign for visual production, retouching, vector work, and publication layout.'],['Collaborative design','Canva and Figma for editable systems, interface planning, and faster team feedback.'],['Web and automation','HTML, CSS, JavaScript, Google Apps Script, Supabase, GitHub Pages, and Google Sheets.'],['Delivery workflow','Google Workspace, organized cloud handoffs, revision tracking, and multi-format file preparation.']]},
remote:{eyebrow:'REMOTE-WORK CAPABILITY',title:'Prepared for structured remote collaboration',intro:'My setup supports design production, large file delivery, meetings, async updates, and overlapping schedules.',cta:'mailto:jannjaravata@gmail.com',sections:[['Workstation','Dedicated Ryzen-based workstation with Adobe production and web-development capability.'],['Connectivity','Fast primary internet connection with a mobile backup for meetings and delivery.'],['Communication','Email, chat, Google Drive, shared documents, async updates, and documented revision rounds.'],['Scheduling','Flexible overlap by arrangement for freelance, part-time, and project-based work.']]},
panpacific:{eyebrow:'PROFESSIONAL EXPERIENCE',title:'Panpacific University',intro:'Since 2018, I have supported university communication through design, content, publication, event, and social media production.',cta:'projects.html',sections:[['Role','Creative Designer, Multimedia Specialist, and Social Media Manager.'],['Responsibilities','Institutional campaigns, announcements, official social content, publications, event materials, and website graphics.'],['Environment','Multiple offices, high-volume requests, strict brand requirements, urgent deadlines, and two-campus communication.'],['Outputs','Enrollment campaigns, achievements, rankings, student advisories, research events, and ongoing content systems.']]},
designlab:{eyebrow:'INDEPENDENT PRACTICE',title:'DesignLab Creative Studio',intro:'DesignLab is my independent practice for client design, digital products, campaign systems, and lightweight web tools.',cta:'projects.html',sections:[['Role','Founder, Creative Director, freelance designer, and creative developer.'],['Services','Social campaigns, branding, publications, mockups, presentation visuals, and digital products.'],['Systems','Portfolio sites, landing pages, trackers, inquiry tools, dashboards, and Google-based workflows.'],['Approach','Designer-led direction, organized revisions, reusable systems, and practical handoff files.']]}
};
function renderSections(items){return items.map(([heading,body])=>`<section><span>${heading}</span><p>${body}</p></section>`).join('');}
function openDetail(key,trigger){const detail=details[key];if(!detail)return;lastTrigger=trigger;eyebrow.textContent=detail.eyebrow;title.textContent=detail.title;intro.textContent=detail.intro;sections.innerHTML=renderSections(detail.sections);cta.href=detail.cta;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modal.querySelector('.project-preview-close')?.focus();}
function closeDetail(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');lastTrigger?.focus();}
document.querySelectorAll('[data-cv-detail]').forEach(button=>button.addEventListener('click',()=>openDetail(button.dataset.cvDetail,button)));document.querySelectorAll('[data-cv-close]').forEach(button=>button.addEventListener('click',closeDetail));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal.classList.contains('is-open'))closeDetail();});document.getElementById('printCvButton')?.addEventListener('click',()=>window.print());